// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQRnzew_i2WWzfm0Q98SO8lPZh863hVT4',
    appId: '1:343705385926:web:e4b940bf3454a852d910c7',
    messagingSenderId: '343705385926',
    projectId: 'fir-auth-73b47',
    authDomain: 'fir-auth-73b47.firebaseapp.com',
    storageBucket: 'fir-auth-73b47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDVdTVoesNtPzHjWWKKOVKk7t_3OWS-Wc',
    appId: '1:343705385926:android:230d892ca63be77ad910c7',
    messagingSenderId: '343705385926',
    projectId: 'fir-auth-73b47',
    storageBucket: 'fir-auth-73b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FWeEu6viUQOBwpzNdrucAGVjddhs-bk',
    appId: '1:343705385926:ios:b8b814860ff09a12d910c7',
    messagingSenderId: '343705385926',
    projectId: 'fir-auth-73b47',
    storageBucket: 'fir-auth-73b47.firebasestorage.app',
    androidClientId: '343705385926-jkieg1ous10tegab1ab9ooln9b1m1o2u.apps.googleusercontent.com',
    iosClientId: '343705385926-vga09rd3bt20k873hfbo1slbq3o1t1ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FWeEu6viUQOBwpzNdrucAGVjddhs-bk',
    appId: '1:343705385926:ios:b8b814860ff09a12d910c7',
    messagingSenderId: '343705385926',
    projectId: 'fir-auth-73b47',
    storageBucket: 'fir-auth-73b47.firebasestorage.app',
    androidClientId: '343705385926-jkieg1ous10tegab1ab9ooln9b1m1o2u.apps.googleusercontent.com',
    iosClientId: '343705385926-vga09rd3bt20k873hfbo1slbq3o1t1ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQRnzew_i2WWzfm0Q98SO8lPZh863hVT4',
    appId: '1:343705385926:web:8f57917b88ea1798d910c7',
    messagingSenderId: '343705385926',
    projectId: 'fir-auth-73b47',
    authDomain: 'fir-auth-73b47.firebaseapp.com',
    storageBucket: 'fir-auth-73b47.firebasestorage.app',
  );

}